// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEx0wxAFxvlcx_D95ZS83tG3R6hozZ6wM',
    appId: '1:416790824993:web:11c2fbd24b9c343f1d7b60',
    messagingSenderId: '416790824993',
    projectId: 'events-c16-7d05d',
    authDomain: 'events-c16-7d05d.firebaseapp.com',
    storageBucket: 'events-c16-7d05d.firebasestorage.app',
    measurementId: 'G-57NBY3DJKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjA5ac26h4vZezy7Ad_pq99_9PabfmGwU',
    appId: '1:416790824993:android:2ee8e3287465d59b1d7b60',
    messagingSenderId: '416790824993',
    projectId: 'events-c16-7d05d',
    storageBucket: 'events-c16-7d05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeH_fLL51tCQUpIMEgd0Mf8-Y0miE38XI',
    appId: '1:416790824993:ios:34422e106d78459b1d7b60',
    messagingSenderId: '416790824993',
    projectId: 'events-c16-7d05d',
    storageBucket: 'events-c16-7d05d.firebasestorage.app',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeH_fLL51tCQUpIMEgd0Mf8-Y0miE38XI',
    appId: '1:416790824993:ios:34422e106d78459b1d7b60',
    messagingSenderId: '416790824993',
    projectId: 'events-c16-7d05d',
    storageBucket: 'events-c16-7d05d.firebasestorage.app',
    iosBundleId: 'com.example.pro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEx0wxAFxvlcx_D95ZS83tG3R6hozZ6wM',
    appId: '1:416790824993:web:73da270da62dfed31d7b60',
    messagingSenderId: '416790824993',
    projectId: 'events-c16-7d05d',
    authDomain: 'events-c16-7d05d.firebaseapp.com',
    storageBucket: 'events-c16-7d05d.firebasestorage.app',
    measurementId: 'G-VCNQQ74K32',
  );

}